import Head from 'next/head'
import React, { useState } from 'react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJs + Tailwind Css Folder Structure</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen justify-center items-center w-screen'>
        <h1 className='text-center text-8xl w-full font-semibold bg-slate-500 py-8 text-white shadow-lg shadow-slate-700/50'>Hello World</h1>
      </main>
    </div>
  )
}
